
apiVersion: v1
kind: Service
metadata:
  name: app-one
  labels:
    app: app-one
spec:
  ports:
    - port: 80
      targetPort: 8080 # First of all there is the redirect of the  is defined in the https://github.com/paulbouwer/hello-kubernetes/blob/main/src/app/server.js
  selector:
    app: app-one
