
apiVersion: v1
kind: Service
metadata:
  name: app-one
  labels:
    app: app-one
spec:
  ports:
    - port: 8888 #source 
      targetPort: 8888 # First of all there is the redirect of the  is defined in the https://github.com/paulbouwer/hello-kubernetes/blob/main/src/app/server.js dest 
  selector:
    app: app-one
